spring:
  application:
    name: flight-producer
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

kafka:
  topic:
    flight: flights

flight:
  socket:
    host: 192.168.8.236
    port: 30003
