spring:
  application:
    name: flight-app

  datasource:
    url: jdbc:postgresql://localhost:5432/flights_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

kafka:
  topic:
    rawFlights: raw-flights
    completedFlights: flights-completed
    flightsOverHome: flights-over-home
    flightsUpdate: flights-update
    deadLetter: flights-dlq

flight:
  socket:
    host: 192.168.8.236
    port: 30003




